#!/bin/sh

set -x

APP=/Applications/Openzro.app
AGENT=/usr/local/bin/openzro
LOG_FILE=/var/log/openzro/client_post_install.log

mkdir -p /var/log/openzro/
mkdir -p /usr/local/bin/

{
    echo "Installing Openzro..."

    if test -d $APP; then
        echo "Openzro app copied successfully."
    else
        echo "Openzro app could not be copied to the Applications folder."
        exit 1
    fi

    ln -fs $APP/Contents/MacOS/openzro $AGENT
    if test -f $AGENT; then
        echo "Openzro binary linked successfully."
    else
        echo "Openzro could not create symlink to /usr/local/bin"
        exit 1
    fi

    $AGENT service install || true
    $AGENT service start || true

    open $APP

    echo "Finished Openzro installation successfully"
    exit 0 # all good
} &> $LOG_FILE

