#!/bin/sh

set -x

LOG_FILE=/var/log/openzro/client_pre_install.log
AGENT=/usr/local/bin/openzro

mkdir -p /var/log/openzro/

{
    # check if it was installed with brew
    brew list --formula | grep openzro
    if [ $? -eq 0 ]
    then
        echo "Openzro has been installed with Brew. Please use Brew to update the package."
        exit 1
    fi
    osascript -e 'quit app "Openzro"' || true
    $AGENT service stop || true

    echo "Preinstall complete"
    exit 0 # all good
} &> $LOG_FILE

