version: 2

project_name: openzro-ui
builds:
  - id: openzro-ui-darwin
    dir: client/ui
    binary: openzro-ui
    env:
      - CGO_ENABLED=1
      - MACOSX_DEPLOYMENT_TARGET=11.0
      - MACOS_DEPLOYMENT_TARGET=11.0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    gomips:
      - hardfloat
      - softfloat
    ldflags:
      - -s -w -X github.com/openzro/openzro/version.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.CommitDate}} -X main.builtBy=goreleaser
    mod_timestamp: "{{ .CommitTimestamp }}"
    tags:
      - load_wgnt_from_rsrc

universal_binaries:
  - id: openzro-ui-darwin

archives:
  - builds:
      - openzro-ui-darwin

checksum:
  name_template: "{{ .ProjectName }}_darwin_checksums.txt"
changelog:
  disable: true
