FROM ubuntu:24.04
RUN apt update && apt install -y ca-certificates && rm -fr /var/cache/apt
ENTRYPOINT [ "/go/bin/openzro-mgmt","management","--log-level","debug"]
CMD ["--log-file", "console"]
COPY openzro-mgmt /go/bin/openzro-mgmt
