"use client";

import Button from "@components/Button";
import { Input } from "@components/Input";
import SkeletonTable from "@components/skeletons/SkeletonTable";
import useFetchApi from "@utils/api";
import dayjs from "dayjs";
import {
  ActivityIcon,
  ArrowDown,
  ArrowRight,
  ArrowUp,
  Ban,
  ChevronDown,
  ChevronRight,
  GlobeIcon,
  Play,
  SearchIcon,
  ShieldCheckIcon,
  Square,
} from "lucide-react";
import React, { useMemo, useState } from "react";
import RoundedFlag from "@/assets/countries/RoundedFlag";
import { usePeers } from "@/contexts/PeersProvider";
import { NetworkTrafficEvent } from "@/interfaces/NetworkTrafficEvent";
import { Peer } from "@/interfaces/Peer";
import { Policy } from "@/interfaces/Policy";

type Props = {
  events?: NetworkTrafficEvent[];
  isLoading: boolean;
};

// FlowGroup correlates every event reported for a single connection.
// flow_id is generated by the peer's conntrack hook so start/end/drop
// of one TCP/UDP/ICMP session always share it; grouping client-side
// avoids an API change and keeps this view a pure presentation layer.
type FlowGroup = {
  flowID: string;
  events: NetworkTrafficEvent[];
  // pre-resolved for the header so the card body doesn't repeat lookups
  reportingPeer?: Peer;
  sourcePeer?: Peer;
  destPeer?: Peer;
  policy?: Policy;
  totalRx: number;
  totalTx: number;
  // latest event timestamp drives card ordering (most recent first)
  latestAt: string;
};

const PAGE_SIZE = 25;

export default function NetworkTrafficTimeline({ events, isLoading }: Props) {
  const { peers } = usePeers();
  const { data: policies } = useFetchApi<Policy[]>("/policies");

  const [search, setSearch] = useState("");
  const [visibleCount, setVisibleCount] = useState(PAGE_SIZE);
  const [expanded, setExpanded] = useState<Record<string, boolean>>({});

  const groups = useMemo(
    () => groupFlows(events ?? [], peers ?? [], policies ?? []),
    [events, peers, policies],
  );

  const filtered = useMemo(() => {
    const q = search.trim().toLowerCase();
    if (!q) return groups;
    return groups.filter((g) => matchesSearch(g, q));
  }, [groups, search]);

  const visible = filtered.slice(0, visibleCount);
  const hasMore = filtered.length > visible.length;

  if (isLoading) return <SkeletonTable />;

  return (
    <div className={"flex flex-col gap-3 px-default pb-8"}>
      <div className={"flex items-center gap-3"}>
        <div className={"relative flex-1 max-w-md"}>
          <SearchIcon
            size={14}
            className={
              "absolute left-3 top-1/2 -translate-y-1/2 text-nb-gray-400"
            }
          />
          <Input
            value={search}
            onChange={(e) => {
              setSearch(e.target.value);
              setVisibleCount(PAGE_SIZE);
            }}
            placeholder={"Search by peer, IP or policy…"}
            className={"pl-9"}
          />
        </div>
        <span className={"text-xs text-nb-gray-300"}>
          {filtered.length} flow{filtered.length === 1 ? "" : "s"}
        </span>
      </div>

      {visible.length === 0 ? (
        <EmptyState hasSearch={search.length > 0} />
      ) : (
        <ul className={"flex flex-col gap-2"}>
          {visible.map((g) => (
            <FlowCard
              key={g.flowID}
              group={g}
              expanded={!!expanded[g.flowID]}
              onToggle={() =>
                setExpanded((prev) => ({
                  ...prev,
                  [g.flowID]: !prev[g.flowID],
                }))
              }
            />
          ))}
        </ul>
      )}

      {hasMore && (
        <div className={"flex justify-center pt-2"}>
          <Button
            variant={"secondary"}
            onClick={() => setVisibleCount((n) => n + PAGE_SIZE)}
          >
            Load more
          </Button>
        </div>
      )}
    </div>
  );
}

function FlowCard({
  group,
  expanded,
  onToggle,
}: {
  group: FlowGroup;
  expanded: boolean;
  onToggle: () => void;
}) {
  const start = group.events.find((e) => e.type === "start");
  const head = start ?? group.events[0];

  return (
    <li
      className={
        "rounded-lg border border-nb-gray-900 bg-nb-gray-940/40 hover:border-nb-gray-800 transition-colors"
      }
    >
      <button
        type={"button"}
        onClick={onToggle}
        className={"w-full text-left px-4 py-3 flex items-start gap-3"}
      >
        <div className={"pt-1 text-nb-gray-400"}>
          {expanded ? <ChevronDown size={14} /> : <ChevronRight size={14} />}
        </div>
        <div className={"flex-1 min-w-0 flex flex-col gap-2"}>
          <FlowHeadline group={group} head={head} />
          <FlowEndpoints group={group} head={head} />
          <FlowFooter group={group} />
        </div>
      </button>

      {expanded && (
        <div
          className={
            "border-t border-nb-gray-900 px-4 py-3 flex flex-col gap-3"
          }
        >
          {group.events
            .slice()
            .sort((a, b) => a.occurred_at.localeCompare(b.occurred_at))
            .map((e) => (
              <TimelineRow key={e.event_id} event={e} group={group} />
            ))}
        </div>
      )}
    </li>
  );
}

function FlowHeadline({
  group,
  head,
}: {
  group: FlowGroup;
  head: NetworkTrafficEvent;
}) {
  const dest = group.destPeer?.name ?? group.destPeer?.hostname ?? head.dest_ip;
  const src =
    group.sourcePeer?.name ?? group.sourcePeer?.hostname ?? head.source_ip;
  const verb = headlineVerb(group);
  const tone = headlineTone(group);

  return (
    <div className={"flex items-center justify-between gap-3"}>
      <div className={"flex items-center gap-2 text-sm text-white min-w-0"}>
        <span className={tone}>
          <ActivityIcon size={14} />
        </span>
        <span className={"truncate"}>
          <strong className={"font-medium"}>{dest}</strong> {verb}{" "}
          <strong className={"font-medium"}>{src}</strong>
        </span>
      </div>
      <span className={"font-mono text-[11px] text-nb-gray-400 shrink-0"}>
        {dayjs(group.latestAt).format("YYYY-MM-DD HH:mm:ss")}
      </span>
    </div>
  );
}

function FlowEndpoints({
  group,
  head,
}: {
  group: FlowGroup;
  head: NetworkTrafficEvent;
}) {
  return (
    <div className={"flex items-center gap-2 text-xs"}>
      <PeerEndpoint
        peer={group.sourcePeer}
        ip={head.source_ip}
        port={head.source_port}
      />
      <ArrowRight size={14} className={"text-nb-gray-500 shrink-0"} />
      <PeerEndpoint
        peer={group.destPeer}
        ip={head.dest_ip}
        port={head.dest_port}
      />
    </div>
  );
}

function FlowFooter({ group }: { group: FlowGroup }) {
  const head = group.events[0];
  return (
    <div
      className={"flex items-center gap-4 text-[11px] text-nb-gray-300 mt-1"}
    >
      <span className={"font-mono uppercase"}>{protocolName(head.protocol)}</span>
      <span className={"flex items-center gap-1"}>
        <ArrowDown size={12} className={"text-sky-400"} />
        {formatBytes(group.totalRx)}
      </span>
      <span className={"flex items-center gap-1"}>
        <ArrowUp size={12} className={"text-violet-400"} />
        {formatBytes(group.totalTx)}
      </span>
      {group.policy && (
        <span
          className={"flex items-center gap-1 text-emerald-400"}
          title={group.policy.description}
        >
          <ShieldCheckIcon size={12} />
          {group.policy.name}
        </span>
      )}
      <span className={"text-nb-gray-500 ml-auto"}>
        {group.events.length} event{group.events.length === 1 ? "" : "s"}
      </span>
    </div>
  );
}

function TimelineRow({
  event,
  group,
}: {
  event: NetworkTrafficEvent;
  group: FlowGroup;
}) {
  const dot = dotFor(event);
  return (
    <div className={"flex items-start gap-3"}>
      <div className={"flex flex-col items-center pt-1"}>
        <span className={dot.cls}>{dot.icon}</span>
      </div>
      <div className={"flex-1 flex flex-col gap-0.5"}>
        <div className={"flex items-center gap-2"}>
          <span className={"text-xs text-white"}>
            {narrativeFor(event, group)}
          </span>
          <span className={"font-mono text-[10px] text-nb-gray-500"}>
            {dayjs(event.occurred_at).format("HH:mm:ss")}
          </span>
        </div>
        {(event.rx_bytes > 0 || event.tx_bytes > 0) && (
          <span className={"font-mono text-[10px] text-nb-gray-400"}>
            ↓ {formatBytes(event.rx_bytes)} · ↑ {formatBytes(event.tx_bytes)}
          </span>
        )}
      </div>
    </div>
  );
}

function PeerEndpoint({
  peer,
  ip,
  port,
}: {
  peer?: Peer;
  ip: string;
  port?: number;
}) {
  return (
    <div
      className={
        "flex items-center gap-2 rounded-md bg-nb-gray-930/60 px-2 py-1 min-w-0"
      }
    >
      {peer?.country_code ? (
        <RoundedFlag country={peer.country_code} size={14} />
      ) : (
        <GlobeIcon size={12} className={"text-nb-gray-400 shrink-0"} />
      )}
      <div className={"flex flex-col min-w-0"}>
        {peer && <span className={"text-xs text-white truncate"}>{peer.name}</span>}
        <span className={"font-mono text-[10px] text-nb-gray-300 truncate"}>
          {port ? `${ip}:${port}` : ip}
        </span>
      </div>
    </div>
  );
}

function EmptyState({ hasSearch }: { hasSearch: boolean }) {
  return (
    <div
      className={
        "rounded-lg border border-dashed border-nb-gray-900 px-6 py-12 text-center"
      }
    >
      <ActivityIcon
        size={28}
        className={"mx-auto mb-3 text-nb-gray-600"}
      />
      <p className={"text-sm text-nb-gray-300"}>
        {hasSearch
          ? "No flows match your search."
          : "No network traffic events yet."}
      </p>
      {!hasSearch && (
        <p className={"text-xs text-nb-gray-500 mt-1"}>
          Once peers start reporting, every TCP / UDP / ICMP connection
          shows up here as a card.
        </p>
      )}
    </div>
  );
}

// groupFlows folds the flat event stream into per-flow_id groups,
// resolves the peers + policy once per group so renders are cheap, and
// orders groups by their latest event so the most recent connections
// rise to the top.
function groupFlows(
  events: NetworkTrafficEvent[],
  peers: Peer[],
  policies: Policy[],
): FlowGroup[] {
  const byID = new Map<string, Peer>();
  const byIP = new Map<string, Peer>();
  for (const p of peers) {
    if (p.id) byID.set(p.id, p);
    if (p.ip) byIP.set(p.ip, p);
  }
  const policyByID = new Map<string, Policy>();
  for (const p of policies) {
    if (p.id) policyByID.set(p.id, p);
  }

  const grouped = new Map<string, FlowGroup>();
  for (const e of events) {
    const key = e.flow_id || e.event_id;
    let g = grouped.get(key);
    if (!g) {
      g = {
        flowID: key,
        events: [],
        reportingPeer: byID.get(e.peer_id),
        sourcePeer: byIP.get(e.source_ip),
        destPeer: byIP.get(e.dest_ip),
        policy: e.rule_id ? policyByID.get(e.rule_id) : undefined,
        totalRx: 0,
        totalTx: 0,
        latestAt: e.occurred_at,
      };
      grouped.set(key, g);
    }
    g.events.push(e);
    g.totalRx += e.rx_bytes;
    g.totalTx += e.tx_bytes;
    if (e.occurred_at > g.latestAt) g.latestAt = e.occurred_at;
    if (!g.policy && e.rule_id) g.policy = policyByID.get(e.rule_id);
  }

  return Array.from(grouped.values()).sort((a, b) =>
    b.latestAt.localeCompare(a.latestAt),
  );
}

function matchesSearch(g: FlowGroup, q: string): boolean {
  const haystack = [
    g.sourcePeer?.name,
    g.sourcePeer?.hostname,
    g.destPeer?.name,
    g.destPeer?.hostname,
    g.reportingPeer?.name,
    g.policy?.name,
    g.events[0]?.source_ip,
    g.events[0]?.dest_ip,
  ];
  return haystack.some((v) => v && v.toLowerCase().includes(q));
}

function headlineVerb(g: FlowGroup): string {
  const types = new Set(g.events.map((e) => e.type));
  if (types.has("drop")) return "blocked connection from";
  if (types.has("end") && !types.has("start"))
    return "stopped connection from";
  if (types.has("end")) return "received connection from";
  return "received connection from";
}

function headlineTone(g: FlowGroup): string {
  const types = new Set(g.events.map((e) => e.type));
  if (types.has("drop")) return "text-red-400";
  if (types.has("end")) return "text-nb-gray-300";
  return "text-emerald-400";
}

function narrativeFor(e: NetworkTrafficEvent, g: FlowGroup): string {
  const dest = g.destPeer?.name ?? e.dest_ip;
  const src = g.sourcePeer?.name ?? e.source_ip;
  switch (e.type) {
    case "start":
      return `${dest} received connection from ${src}`;
    case "end":
      return `Connection between ${dest} and ${src} ended`;
    case "drop":
      return `${dest} blocked connection from ${src}`;
    default:
      return `Event between ${dest} and ${src}`;
  }
}

function dotFor(e: NetworkTrafficEvent): {
  icon: React.ReactNode;
  cls: string;
} {
  switch (e.type) {
    case "start":
      return {
        icon: <Play size={10} />,
        cls:
          "inline-flex items-center justify-center w-5 h-5 rounded-full bg-emerald-500/15 text-emerald-400",
      };
    case "end":
      return {
        icon: <Square size={10} />,
        cls:
          "inline-flex items-center justify-center w-5 h-5 rounded-full bg-nb-gray-800 text-nb-gray-300",
      };
    case "drop":
      return {
        icon: <Ban size={10} />,
        cls:
          "inline-flex items-center justify-center w-5 h-5 rounded-full bg-red-500/15 text-red-400",
      };
    default:
      return {
        icon: null,
        cls:
          "inline-flex items-center justify-center w-5 h-5 rounded-full bg-nb-gray-900 text-nb-gray-500",
      };
  }
}

// IANA protocol numbers for the common cases. Unknown numbers render
// as "p<n>" so dashboards always show something readable.
function protocolName(protocol: number): string {
  switch (protocol) {
    case 1:
      return "icmp";
    case 6:
      return "tcp";
    case 17:
      return "udp";
    case 58:
      return "icmpv6";
    case 132:
      return "sctp";
    default:
      return `p${protocol}`;
  }
}

function formatBytes(b: number): string {
  if (b < 1024) return `${b} B`;
  if (b < 1024 * 1024) return `${(b / 1024).toFixed(1)} KB`;
  if (b < 1024 * 1024 * 1024) return `${(b / 1024 / 1024).toFixed(1)} MB`;
  return `${(b / 1024 / 1024 / 1024).toFixed(2)} GB`;
}
